#include "telas.h"

int main(){
    inicio();
    return 0;
}

/*
    TENTAR FAZER SE DER TEMPO UMA FUNÇÃO QUE VERIFICA SE DADOS NUMÉRICOS NÃO ESTÃO INCONSISTENTES.
    O PROGRAMA DEVE COLETAR TODOS OS DADOS COMO STRING PARA TER MAIOR FLEXIBILIDADE PARA FAZER A PROMOÇÃO DE TIPO.
*/
